import "./globals.css";
import Header from "./components/header";

// remote font import
import { Bungee_Spice } from "next/font/google";

// remote font kurulumu
const bungeeSpice = Bungee_Spice({
  subsets: ["latin"],
  variable: "--font-bungee-spice",
  weight: "400",
});

// local font import
import LocalFont from "next/font/local";

// local font kurulumu
const extraBlue = LocalFont({
  src: "./assets/extra-blue.ttf",
  variable: "--font-extra-blue",
  weight: "100 700",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        //  style={{ fontFamily: bungeeSpice.style.fontFamily }}
        className={`${bungeeSpice.variable} ${extraBlue.variable} antialiased`}
      >
        <Header />

        <div className="font-extra-blue">{children}</div>
      </body>
    </html>
  );
}
